"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";

type OwnerStatementPdfProps = {
  reportData: Record<string, unknown>;
  orgName: string;
  orgRuc?: string | null;
  orgQrImageUrl?: string | null;
  periodLabel: string;
  locale: string;
  isEn: boolean;
};

function fmt(value: unknown, currency = "PYG", locale = "es-PY"): string {
  const n = typeof value === "number" ? value : Number(value);
  if (Number.isNaN(n)) return "-";
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "PYG" ? 0 : 2,
    maximumFractionDigits: currency === "PYG" ? 0 : 2,
  }).format(n);
}

function pct(value: unknown): string {
  const n = typeof value === "number" ? value : Number(value);
  if (Number.isNaN(n)) return "-";
  return `${(n * 100).toFixed(1)}%`;
}

/**
 * PDF generation logic — extracted to module scope so the React Compiler
 * can optimize the component without encountering value blocks in try/catch.
 */
async function generateOwnerStatementPdf(
  props: OwnerStatementPdfProps
): Promise<void> {
  const {
    reportData,
    orgName,
    orgRuc,
    orgQrImageUrl,
    periodLabel,
    locale,
    isEn,
  } = props;

  const titleText = isEn
    ? "Owner Statement"
    : "Estado de Cuenta del Propietario";
  const summaryTitle = isEn ? "Summary" : "Resumen";
  const itemLabel = isEn ? "Item" : "Concepto";
  const amountLabel = isEn ? "Amount" : "Monto";
  const netPayoutLabel = isEn ? "Net Payout" : "Pago Neto";
  const performanceTitle = isEn ? "Performance" : "Rendimiento";
  const metricLabel = isEn ? "Metric" : "Métrica";
  const valueLabel = isEn ? "Value" : "Valor";
  const scanLabel = isEn ? "Scan to verify" : "Escanear para verificar";
  const generatedByPrefix = isEn ? "Generated by" : "Generado por";
  const pagePrefix = isEn ? "Page" : "Página";
  const filePrefix = isEn ? "owner-statement" : "estado-cuenta";

  let leaseCollections = reportData.lease_collections;
  if (leaseCollections == null) {
    leaseCollections = reportData.total_collections;
  }
  let expenses = reportData.expenses;
  if (expenses == null) {
    expenses = reportData.operating_expenses;
  }
  let taxesCollected = reportData.taxes_collected;
  if (taxesCollected == null) {
    taxesCollected = reportData.taxes;
  }

  const summaryData = [
    [
      isEn ? "Gross Revenue" : "Ingresos Brutos",
      fmt(reportData.gross_revenue, "PYG", locale),
    ],
    [
      isEn ? "Lease Collections" : "Cobros de Alquiler",
      fmt(leaseCollections, "PYG", locale),
    ],
    [
      isEn ? "Service Fees" : "Cuotas de Servicio",
      fmt(reportData.service_fees, "PYG", locale),
    ],
    [isEn ? "Expenses" : "Gastos", fmt(expenses, "PYG", locale)],
    [
      isEn ? "Platform Fees" : "Comisiones de Plataforma",
      fmt(reportData.platform_fees, "PYG", locale),
    ],
    [isEn ? "Taxes" : "Impuestos", fmt(taxesCollected, "PYG", locale)],
  ].filter(([, val]) => val !== "-");

  const netPayout = fmt(reportData.net_payout, "PYG", locale);

  const perfData: string[][] = [];
  if (reportData.occupancy_rate !== undefined) {
    perfData.push([
      isEn ? "Occupancy Rate" : "Tasa de Ocupación",
      pct(reportData.occupancy_rate),
    ]);
  }
  if (reportData.collection_rate !== undefined) {
    perfData.push([
      isEn ? "Collection Rate" : "Tasa de Cobro",
      pct(reportData.collection_rate),
    ]);
  }
  if (reportData.total_units !== undefined) {
    perfData.push([
      isEn ? "Total Units" : "Total Unidades",
      String(reportData.total_units),
    ]);
  }
  if (reportData.active_leases !== undefined) {
    perfData.push([
      isEn ? "Active Leases" : "Contratos Activos",
      String(reportData.active_leases),
    ]);
  }

  let hasPerformance = false;
  if (reportData.occupancy_rate !== undefined) {
    hasPerformance = true;
  }
  if (reportData.collection_rate !== undefined) {
    hasPerformance = true;
  }
  const qrUrl = orgQrImageUrl;

  const jsPDFModule = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const jsPDF = jsPDFModule.default;
  const autoTable = autoTableModule.default;

  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    let y = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(titleText, margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(orgName, margin, y);
    y += 5;
    if (orgRuc) {
      doc.text(`RUC: ${orgRuc}`, margin, y);
      y += 5;
    }
    doc.text(periodLabel, margin, y);
    y += 3;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Summary cards
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(summaryTitle, margin, y);
    y += 7;

    autoTable(doc, {
      startY: y,
      head: [[itemLabel, amountLabel]],
      body: summaryData,
      theme: "striped",
      headStyles: { fillColor: [41, 41, 41], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: { 1: { halign: "right" } },
      margin: { left: margin, right: margin },
    });

    // @ts-expect-error - jspdf-autotable adds lastAutoTable to doc
    y = doc.lastAutoTable.finalY + 10;

    // Net payout highlight
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${netPayoutLabel}: ${netPayout}`, margin, y);
    y += 10;

    // Occupancy & Performance
    if (hasPerformance) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(performanceTitle, margin, y);
      y += 7;

      if (perfData.length > 0) {
        autoTable(doc, {
          startY: y,
          head: [[metricLabel, valueLabel]],
          body: perfData,
          theme: "striped",
          headStyles: { fillColor: [41, 41, 41], fontSize: 9 },
          bodyStyles: { fontSize: 9 },
          columnStyles: { 1: { halign: "right" } },
          margin: { left: margin, right: margin },
        });
      }
    }

    // QR code image (if available)
    if (qrUrl) {
      try {
        const response = await fetch(qrUrl);
        const blob = await response.blob();
        const reader = new FileReader();
        const dataUrl = await new Promise<string>((resolve) => {
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
        const qrSize = 30;
        const pageHeight = doc.internal.pageSize.getHeight();
        if (y + qrSize + 20 > pageHeight) {
          doc.addPage();
          y = 20;
        }
        doc.addImage(dataUrl, "PNG", margin, y, qrSize, qrSize);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(scanLabel, margin + qrSize + 4, y + qrSize / 2);
        y += qrSize + 10;
      } catch {
        // QR image fetch failed — skip silently
      }
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    const generatedDate = new Date().toLocaleDateString(locale);
    const footerLeft = `${generatedByPrefix} Casaora \u2014 ${generatedDate}`;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(150);
      const footerY = doc.internal.pageSize.getHeight() - 10;
      const footerRight = `${pagePrefix} ${String(i)}/${String(pageCount)}`;
      doc.text(footerLeft, margin, footerY);
      doc.text(footerRight, pageWidth - margin, footerY, { align: "right" });
    }

    // Download
    const fileName = `${filePrefix}-${periodLabel.replace(/\s+/g, "-")}.pdf`;
    doc.save(fileName);
  } catch (err) {
    console.error("PDF generation failed:", err);
  }
}

export function OwnerStatementPdfButton({
  reportData,
  orgName,
  orgRuc,
  orgQrImageUrl,
  periodLabel,
  locale,
  isEn,
}: OwnerStatementPdfProps) {
  const [generating, setGenerating] = useState(false);

  const handleDownload = async () => {
    if (generating) return;
    setGenerating(true);
    await generateOwnerStatementPdf({
      reportData,
      orgName,
      orgRuc,
      orgQrImageUrl,
      periodLabel,
      locale,
      isEn,
    });
    setGenerating(false);
  };

  return (
    <Button
      disabled={generating}
      onClick={handleDownload}
      size="sm"
      variant="outline"
    >
      {generating ? (
        <>
          <Spinner size="sm" />
          {isEn ? "Generating..." : "Generando..."}
        </>
      ) : isEn ? (
        "Download PDF"
      ) : (
        "Descargar PDF"
      )}
    </Button>
  );
}
