/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** Format: date-time */
                            now: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user context */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile and memberships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Organization list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Organization"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationInput"];
                };
            };
            responses: {
                /** @description Organization created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    org_id: components["parameters"]["OrgIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Organization detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update organization */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    org_id: components["parameters"]["OrgIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationInput"];
                };
            };
            responses: {
                /** @description Organization updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    org_id: components["parameters"]["OrgIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["OrganizationMember"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add organization member */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    org_id: components["parameters"]["OrgIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddOrganizationMemberInput"];
                };
            };
            responses: {
                /** @description Member added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationMember"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List properties */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    status?: components["schemas"]["PropertyStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Property"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create property */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePropertyInput"];
                };
            };
            responses: {
                /** @description Property created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get property by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    property_id: components["parameters"]["PropertyIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update property */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    property_id: components["parameters"]["PropertyIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePropertyInput"];
                };
            };
            responses: {
                /** @description Property updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List units */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    property_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unit list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Unit"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create unit */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUnitInput"];
                };
            };
            responses: {
                /** @description Unit created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unit by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    unit_id: components["parameters"]["UnitIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unit detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update unit */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    unit_id: components["parameters"]["UnitIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUnitInput"];
                };
            };
            responses: {
                /** @description Unit updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List channels */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Channel"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChannelInput"];
                };
            };
            responses: {
                /** @description Channel created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List listings */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    unit_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listing list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Listing"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create listing */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIntegrationInput"];
                };
            };
            responses: {
                /** @description Listing created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Listing"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{integration_id}/sync-ical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger iCal sync for listing */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    integration_id: components["parameters"]["ListingIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "queued";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List guests */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    /** @description Search by name/email/phone */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guest list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Guest"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create guest */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGuestInput"];
                };
            };
            responses: {
                /** @description Guest created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guests/{guest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get guest by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guest_id: components["parameters"]["GuestIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guest detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guest"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update guest */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guest_id: components["parameters"]["GuestIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGuestInput"];
                };
            };
            responses: {
                /** @description Guest updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guest"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reservations */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    unit_id?: string;
                    status?: components["schemas"]["ReservationStatus"];
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reservation list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Reservation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create reservation
         * @description Creates a reservation. API must enforce no overlapping active reservations
         *     for the same unit (`pending`, `confirmed`, `checked_in`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReservationInput"];
                };
            };
            responses: {
                /** @description Reservation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                /** @description Overlap or duplicate external reservation id */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get reservation by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservation_id: components["parameters"]["ReservationIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reservation detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update reservation */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservation_id: components["parameters"]["ReservationIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateReservationInput"];
                };
            };
            responses: {
                /** @description Reservation updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservations/{reservation_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition reservation status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservation_id: components["parameters"]["ReservationIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["ReservationStatus"];
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Status transitioned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                /** @description Invalid transition */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unit availability window */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    unit_id: string;
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Availability response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            unit_id: string;
                            /** Format: date */
                            from: string;
                            /** Format: date */
                            to: string;
                            unavailable_periods: components["schemas"]["DateRange"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendar blocks */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    unit_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Block list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CalendarBlock"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create calendar block */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarBlockInput"];
                };
            };
            responses: {
                /** @description Block created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarBlock"];
                    };
                };
                /** @description Block overlaps existing block */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    status?: components["schemas"]["TaskStatus"];
                    assigned_user_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Task"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskInput"];
                };
            };
            responses: {
                /** @description Task created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskInput"];
                };
            };
            responses: {
                /** @description Task updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        completion_notes?: string;
                    };
                };
            };
            responses: {
                /** @description Task marked done */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List expenses */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    from?: string;
                    to?: string;
                    category?: components["schemas"]["ExpenseCategory"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Expense list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Expense"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create expense */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExpenseInput"];
                };
            };
            responses: {
                /** @description Expense created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner-statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owner statements */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    status?: components["schemas"]["StatementStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statement list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["OwnerStatement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Generate draft owner statement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOwnerStatementInput"];
                };
            };
            responses: {
                /** @description Statement created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerStatement"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner-statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get owner statement by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    statement_id: components["parameters"]["StatementIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statement detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerStatement"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner-statements/{statement_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize owner statement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    statement_id: components["parameters"]["StatementIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statement finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerStatement"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/message-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List message templates */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    channel?: components["schemas"]["MessageChannel"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MessageTemplate"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create message template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMessageTemplateInput"];
                };
            };
            responses: {
                /** @description Template created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageTemplate"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue outbound message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageInput"];
                };
            };
            responses: {
                /** @description Message queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageLog"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/owner-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner summary report */
        get: {
            parameters: {
                query: {
                    org_id: components["parameters"]["OrgIdQuery"];
                    from: string;
                    to: string;
                    property_id?: string;
                    unit_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Summary metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerSummaryReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound provider webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "airbnb" | "bookingcom" | "whatsapp" | "other";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Event accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "accepted";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        /** @enum {string} */
        Currency: "PYG" | "USD";
        /** @enum {string} */
        MemberRole: "owner_admin" | "operator" | "cleaner" | "accountant" | "viewer";
        /** @enum {string} */
        PropertyStatus: "active" | "inactive";
        /** @enum {string} */
        ChannelKind: "airbnb" | "bookingcom" | "direct" | "vrbo" | "other";
        /** @enum {string} */
        ReservationStatus: "pending" | "confirmed" | "checked_in" | "checked_out" | "cancelled" | "no_show";
        /** @enum {string} */
        TaskType: "cleaning" | "maintenance" | "check_in" | "check_out" | "inspection" | "custom";
        /** @enum {string} */
        TaskStatus: "todo" | "in_progress" | "done" | "cancelled";
        /** @enum {string} */
        PriorityLevel: "low" | "medium" | "high" | "urgent";
        /** @enum {string} */
        ExpenseCategory: "cleaning" | "maintenance" | "utilities" | "supplies" | "platform_fee" | "tax" | "staff" | "other";
        /** @enum {string} */
        PaymentMethod: "bank_transfer" | "cash" | "card" | "qr" | "other";
        /** @enum {string} */
        StatementStatus: "draft" | "finalized" | "sent" | "paid";
        /** @enum {string} */
        MessageChannel: "whatsapp" | "email" | "sms";
        /** @enum {string} */
        MessageStatus: "queued" | "sent" | "failed";
        Error: {
            error: string;
            message: string;
            code?: string;
        };
        User: {
            id: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            full_name: string;
            phone_e164?: string | null;
        };
        Organization: {
            id: components["schemas"]["UUID"];
            name: string;
            legal_name?: string | null;
            ruc?: string | null;
            default_currency: components["schemas"]["Currency"];
            timezone: string;
            country_code?: string;
            owner_user_id: components["schemas"]["UUID"];
            /** Format: date-time */
            created_at: string;
        };
        OrganizationMember: {
            organization_id: components["schemas"]["UUID"];
            user_id: components["schemas"]["UUID"];
            role: components["schemas"]["MemberRole"];
            is_primary?: boolean;
            /** Format: date-time */
            joined_at: string;
        };
        Property: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            name: string;
            code?: string | null;
            status: components["schemas"]["PropertyStatus"];
            address_line1?: string | null;
            address_line2?: string | null;
            city: string;
            region?: string | null;
            neighborhood?: string | null;
            postal_code?: string | null;
            country_code: string;
            latitude?: number | null;
            longitude?: number | null;
            property_type?: string | null;
            building_amenities?: string[] | null;
            access_instructions?: string | null;
            shared_wifi_name?: string | null;
            shared_wifi_password?: string | null;
            asset_owner_organization_id?: components["schemas"]["UUID"] | null;
            asset_owner_name?: string | null;
        };
        Unit: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            property_id: components["schemas"]["UUID"];
            code: string;
            name: string;
            unit_type?: string;
            condition_status?: string;
            max_guests: number;
            beds_count?: number;
            bedrooms: number;
            bathrooms: number;
            floor_level?: number | null;
            area_sqm?: number | null;
            square_meters?: number | null;
            unit_amenities?: string[] | null;
            bed_configuration?: unknown[] | null;
            base_price_nightly?: number;
            base_price_monthly?: number;
            default_nightly_rate?: number;
            default_cleaning_fee?: number;
            currency: components["schemas"]["Currency"];
            is_active: boolean;
        };
        Channel: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            kind: components["schemas"]["ChannelKind"];
            name: string;
            is_active: boolean;
        };
        Listing: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            external_listing_id?: string | null;
            public_name: string;
            /** Format: uri */
            ical_import_url?: string | null;
            is_active: boolean;
            channel_kind?: string;
            channel_name?: string;
            external_account_ref?: string | null;
        };
        Guest: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            full_name: string;
            /** Format: email */
            email?: string | null;
            phone_e164?: string | null;
        };
        Reservation: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            integration_id?: components["schemas"]["UUID"];
            guest_id?: components["schemas"]["UUID"];
            external_reservation_id?: string | null;
            status: components["schemas"]["ReservationStatus"];
            source: string;
            /** Format: date */
            check_in_date: string;
            /** Format: date */
            check_out_date: string;
            adults?: number;
            children?: number;
            infants?: number;
            pets?: number;
            currency: components["schemas"]["Currency"];
            total_amount: number;
            amount_paid: number;
            owner_payout_estimate: number;
        };
        DateRange: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        CalendarBlock: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            source: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            reason?: string | null;
        };
        Task: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            reservation_id?: components["schemas"]["UUID"];
            assigned_user_id?: components["schemas"]["UUID"];
            type: components["schemas"]["TaskType"];
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["PriorityLevel"];
            title: string;
            description?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Expense: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            category: components["schemas"]["ExpenseCategory"];
            /** Format: date */
            expense_date: string;
            amount: number;
            currency: components["schemas"]["Currency"];
            payment_method: components["schemas"]["PaymentMethod"];
            invoice_number?: string | null;
            invoice_ruc?: string | null;
        };
        OwnerStatement: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            currency: components["schemas"]["Currency"];
            gross_revenue: number;
            platform_fees: number;
            taxes_collected: number;
            operating_expenses: number;
            net_payout: number;
            status: components["schemas"]["StatementStatus"];
        };
        MessageTemplate: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            template_key: string;
            name: string;
            channel: components["schemas"]["MessageChannel"];
            language_code: string;
            subject?: string | null;
            body: string;
            variables: string[];
            is_active: boolean;
        };
        MessageLog: {
            id: components["schemas"]["UUID"];
            organization_id: components["schemas"]["UUID"];
            reservation_id?: components["schemas"]["UUID"];
            guest_id?: components["schemas"]["UUID"];
            channel: components["schemas"]["MessageChannel"];
            recipient: string;
            status: components["schemas"]["MessageStatus"];
            /** Format: date-time */
            scheduled_at?: string | null;
        };
        OwnerSummaryReport: {
            organization_id: components["schemas"]["UUID"];
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @description Value from 0 to 1 */
            occupancy_rate: number;
            gross_revenue: number;
            expenses: number;
            net_payout: number;
        };
        CreateOrganizationInput: {
            name: string;
            legal_name?: string;
            ruc?: string;
            default_currency?: components["schemas"]["Currency"];
            timezone?: string;
        };
        UpdateOrganizationInput: {
            name?: string;
            legal_name?: string;
            ruc?: string;
            profile_type?: string;
            default_currency?: components["schemas"]["Currency"];
            timezone?: string;
            bank_name?: string;
            bank_account_number?: string;
            bank_account_holder?: string;
            qr_image_url?: string;
            logo_url?: string;
        };
        AddOrganizationMemberInput: {
            user_id: components["schemas"]["UUID"];
            role: components["schemas"]["MemberRole"];
        };
        CreatePropertyInput: {
            organization_id: components["schemas"]["UUID"];
            name: string;
            code?: string;
            status?: components["schemas"]["PropertyStatus"];
            address_line1?: string;
            address_line2?: string;
            city?: string;
            region?: string;
            neighborhood?: string;
            postal_code?: string;
            country_code?: string;
            latitude?: number;
            longitude?: number;
            property_type?: string;
            building_amenities?: string[];
            access_instructions?: string;
            shared_wifi_name?: string;
            shared_wifi_password?: string;
            asset_owner_organization_id?: components["schemas"]["UUID"];
            asset_owner_name?: string;
        };
        UpdatePropertyInput: {
            name?: string;
            status?: components["schemas"]["PropertyStatus"];
            address_line1?: string;
            address_line2?: string;
            city?: string;
            region?: string;
            neighborhood?: string;
            postal_code?: string;
            country_code?: string;
            latitude?: number;
            longitude?: number;
            property_type?: string;
            building_amenities?: string[];
            access_instructions?: string;
            shared_wifi_name?: string;
            shared_wifi_password?: string;
            asset_owner_organization_id?: components["schemas"]["UUID"];
            asset_owner_name?: string;
        };
        CreateUnitInput: {
            organization_id: components["schemas"]["UUID"];
            property_id: components["schemas"]["UUID"];
            code: string;
            name: string;
            unit_type?: string;
            max_guests?: number;
            beds_count?: number;
            bedrooms?: number;
            bathrooms?: number;
            floor_level?: number;
            area_sqm?: number;
            square_meters?: number;
            unit_amenities?: string[];
            bed_configuration?: unknown[];
            condition_status?: string;
            base_price_nightly?: number;
            base_price_monthly?: number;
            default_nightly_rate?: number;
            default_cleaning_fee?: number;
            currency?: components["schemas"]["Currency"];
            is_active?: boolean;
        };
        UpdateUnitInput: {
            name?: string;
            unit_type?: string;
            max_guests?: number;
            beds_count?: number;
            bedrooms?: number;
            bathrooms?: number;
            floor_level?: number;
            area_sqm?: number;
            square_meters?: number;
            unit_amenities?: string[];
            bed_configuration?: unknown[];
            condition_status?: string;
            base_price_nightly?: number;
            base_price_monthly?: number;
            default_nightly_rate?: number;
            default_cleaning_fee?: number;
            currency?: components["schemas"]["Currency"];
            is_active?: boolean;
        };
        CreateChannelInput: {
            organization_id: components["schemas"]["UUID"];
            kind: components["schemas"]["ChannelKind"];
            name: string;
        };
        CreateIntegrationInput: {
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            channel_kind: string;
            channel_name: string;
            external_listing_id?: string;
            public_name: string;
            /** Format: uri */
            ical_import_url?: string;
            external_account_ref?: string;
        };
        CreateGuestInput: {
            organization_id: components["schemas"]["UUID"];
            full_name: string;
            /** Format: email */
            email?: string;
            phone_e164?: string;
        };
        UpdateGuestInput: {
            full_name?: string;
            /** Format: email */
            email?: string;
            phone_e164?: string;
            notes?: string;
        };
        CreateReservationInput: {
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            integration_id?: components["schemas"]["UUID"];
            guest_id?: components["schemas"]["UUID"];
            external_reservation_id?: string;
            /** @default manual */
            source: string;
            /** Format: date */
            check_in_date: string;
            /** Format: date */
            check_out_date: string;
            adults?: number;
            children?: number;
            infants?: number;
            pets?: number;
            currency?: components["schemas"]["Currency"];
            nightly_rate?: number;
            cleaning_fee?: number;
            tax_amount?: number;
            extra_fees?: number;
            discount_amount?: number;
            total_amount: number;
            payment_method?: components["schemas"]["PaymentMethod"];
            notes?: string;
        };
        UpdateReservationInput: {
            guest_id?: components["schemas"]["UUID"];
            status?: components["schemas"]["ReservationStatus"];
            payment_method?: components["schemas"]["PaymentMethod"];
            amount_paid?: number;
            notes?: string;
        };
        CreateCalendarBlockInput: {
            organization_id: components["schemas"]["UUID"];
            unit_id: components["schemas"]["UUID"];
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            reason?: string;
        };
        CreateTaskInput: {
            organization_id: components["schemas"]["UUID"];
            property_id?: components["schemas"]["UUID"];
            unit_id?: components["schemas"]["UUID"];
            reservation_id?: components["schemas"]["UUID"];
            assigned_user_id?: components["schemas"]["UUID"];
            type?: components["schemas"]["TaskType"];
            priority?: components["schemas"]["PriorityLevel"];
            title: string;
            description?: string;
            /** Format: date-time */
            due_at?: string;
        };
        UpdateTaskInput: {
            assigned_user_id?: components["schemas"]["UUID"];
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["PriorityLevel"];
            title?: string;
            description?: string;
            /** Format: date-time */
            due_at?: string;
        };
        CreateExpenseInput: {
            organization_id: components["schemas"]["UUID"];
            property_id?: components["schemas"]["UUID"];
            unit_id?: components["schemas"]["UUID"];
            reservation_id?: components["schemas"]["UUID"];
            category: components["schemas"]["ExpenseCategory"];
            vendor_name?: string;
            /** Format: date */
            expense_date: string;
            amount: number;
            currency?: components["schemas"]["Currency"];
            fx_rate_to_pyg?: number;
            payment_method?: components["schemas"]["PaymentMethod"];
            invoice_number?: string;
            invoice_ruc?: string;
            /** Format: uri */
            receipt_url?: string;
            notes?: string;
        };
        CreateOwnerStatementInput: {
            organization_id: components["schemas"]["UUID"];
            property_id?: components["schemas"]["UUID"];
            unit_id?: components["schemas"]["UUID"];
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            currency?: components["schemas"]["Currency"];
        };
        CreateMessageTemplateInput: {
            organization_id: components["schemas"]["UUID"];
            template_key: string;
            name: string;
            channel: components["schemas"]["MessageChannel"];
            language_code?: string;
            subject?: string;
            body: string;
            variables?: string[];
        };
        SendMessageInput: {
            organization_id: components["schemas"]["UUID"];
            reservation_id?: components["schemas"]["UUID"];
            guest_id?: components["schemas"]["UUID"];
            template_id?: components["schemas"]["UUID"];
            channel: components["schemas"]["MessageChannel"];
            recipient: string;
            variables?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            scheduled_at?: string;
        };
        MeResponse: {
            user: components["schemas"]["User"];
            memberships: components["schemas"]["OrganizationMember"][];
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authorized for this resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgIdPath: string;
        OrgIdQuery: string;
        PropertyIdPath: string;
        UnitIdPath: string;
        ListingIdPath: string;
        GuestIdPath: string;
        ReservationIdPath: string;
        TaskIdPath: string;
        StatementIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
