export const PROPERTY_TYPES = [
  { value: "apartment", labelEn: "Apartment", labelEs: "Departamento" },
  { value: "house", labelEn: "House", labelEs: "Casa" },
  { value: "studio", labelEn: "Studio", labelEs: "Monoambiente" },
] as const;

export const NEIGHBORHOODS: Record<string, string[]> = {
  asuncion: [
    "Centro",
    "Villa Morra",
    "Carmelitas",
    "Recoleta",
    "Manorá",
    "Las Mercedes",
    "Sajonia",
    "Barrio Jara",
    "Herrera",
    "Mburucuyá",
    "San Roque",
    "Loma Pytá",
    "Zeballos Cué",
    "Tacumbú",
    "Republicano",
  ],
  "ciudad del este": [
    "Centro",
    "San Juan",
    "Boquerón",
    "Área 1",
    "Área 2",
    "Área 3",
    "Km 4",
    "Km 7",
  ],
  encarnacion: [
    "Centro",
    "San Pedro",
    "Pacú Cuá",
    "Zona Alta",
    "San Isidro",
    "Costanera",
  ],
  luque: [
    "Centro",
    "Segundo Barrio",
    "Loma Merlo",
    "Isla Bogado",
    "San Lorenzo del Campo Grande",
  ],
  "san lorenzo": [
    "Centro",
    "Ciudad Nueva",
    "Laurelty",
    "San Miguel",
    "Reducto",
  ],
  lambare: [
    "Centro",
    "Valle Apu'a",
    "San Isidro",
    "Cacique Lambaré",
  ],
  "fernando de la mora": [
    "Zona Norte",
    "Zona Sur",
    "Centro",
    "Augusto Roa Bastos",
  ],
  capiata: [
    "Centro",
    "Km 18",
    "Km 20",
    "Km 22",
  ],
  "mariano roque alonso": [
    "Centro",
    "San Miguel",
    "Mbachio",
  ],
  itaugua: [
    "Centro",
    "Mbocayaty",
    "Potirendá",
  ],
  "villa elisa": [
    "Centro",
    "Ykua Dure",
    "Colonia Elisa",
  ],
  aregua: [
    "Centro",
    "San Miguel",
    "Isla Valle",
    "Cerrito",
  ],
  ypacarai: [
    "Centro",
    "San Blas",
    "Costa del Lago",
  ],
  "san bernardino": [
    "Centro",
    "Costanera",
    "Mbatoví",
    "Las Piedras",
  ],
};

export const AMENITY_PRESETS = [
  { value: "Wifi", labelEn: "Wifi", labelEs: "Wifi" },
  { value: "Parking", labelEn: "Parking", labelEs: "Estacionamiento" },
  { value: "Air conditioning", labelEn: "Air conditioning", labelEs: "Aire acondicionado" },
  { value: "Gym", labelEn: "Gym", labelEs: "Gimnasio" },
  { value: "Laundry", labelEn: "Laundry", labelEs: "Lavandería" },
  { value: "Security", labelEn: "Security", labelEs: "Seguridad" },
  { value: "Pool", labelEn: "Pool", labelEs: "Piscina" },
  { value: "Elevator", labelEn: "Elevator", labelEs: "Ascensor" },
  { value: "Balcony", labelEn: "Balcony", labelEs: "Balcón" },
  { value: "Storage", labelEn: "Storage", labelEs: "Depósito" },
] as const;
