"use client";

import {
  Calendar02Icon,
  Message01Icon,
  PlusSignIcon,
  Ticket01Icon,
} from "@hugeicons/core-free-icons";
import Link from "next/link";
import type { DataTableRow } from "@/components/ui/data-table";
import { Icon } from "@/components/ui/icon";
import { StatusBadge } from "@/components/ui/status-badge";
import {
  asNumber,
  asString,
  BOARD_LANES,
  formatDueLabel,
  localizedPriorityLabel,
  localizedTaskStatusLabel,
  localizedTaskTypeLabel,
  priorityTone,
  shortId,
} from "@/lib/features/tasks/helpers";

export function TaskBoard({
  isEn,
  locale,
  rows,
  onNewTask,
}: {
  isEn: boolean;
  locale: "es-PY" | "en-US";
  rows: DataTableRow[];
  onNewTask: () => void;
}) {
  const boardLanes = BOARD_LANES.map((lane) => {
    const laneRows = rows
      .filter(
        (row) => asString(row.status).trim().toLowerCase() === lane.status
      )
      .sort((left, right) =>
        asString(right.due_at).localeCompare(asString(left.due_at))
      );
    return { ...lane, rows: laneRows };
  });

  return (
    <section className="grid gap-3 xl:grid-cols-3">
      {boardLanes.map((lane) => (
        <article
          className="glass-surface rounded-3xl p-3"
          key={lane.key}
        >
          <div className="mb-2 flex items-center justify-between">
            <p className="font-semibold text-lg">
              {localizedTaskStatusLabel(isEn, lane.status)}
            </p>
            <StatusBadge
              label={String(lane.rows.length)}
              tone="neutral"
              value={lane.status}
            />
          </div>

          <div className="max-h-[600px] space-y-2 overflow-y-auto">
            {lane.rows.length === 0 ? (
              <div className="rounded-2xl border border-border/80 border-dashed px-3 py-4 text-muted-foreground text-sm">
                {isEn
                  ? "No tasks in this lane."
                  : "Sin tareas en esta columna."}
              </div>
            ) : (
              lane.rows.map((row) => (
                <BoardCard
                  isEn={isEn}
                  key={asString(row.id)}
                  locale={locale}
                  row={row}
                />
              ))
            )}

            <button
              className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-2xl border border-border/70 text-sm transition-colors hover:bg-muted/40"
              onClick={onNewTask}
              type="button"
            >
              <Icon icon={PlusSignIcon} size={15} />
              {isEn ? "Add Task" : "Agregar tarea"}
            </button>
          </div>
        </article>
      ))}
    </section>
  );
}

function BoardCard({
  isEn,
  locale,
  row,
}: {
  isEn: boolean;
  locale: "es-PY" | "en-US";
  row: DataTableRow;
}) {
  const taskId = asString(row.id).trim();
  const title = asString(row.title).trim();
  const typeValue = asString(row.type).trim();
  const priorityValue = asString(row.priority).trim();
  const statusValue = asString(row.status).trim();
  const statusLabel = asString(row.status_label).trim();
  const description = asString(row.description).trim();
  const autoGenerated = Boolean(row.auto_generated);
  const automationSource = asString(row.automation_source).trim();
  const checklistTotal = asNumber(row.checklist_total);
  const checklistCompleted = asNumber(row.checklist_completed);
  const dueLabel = formatDueLabel(locale, asString(row.due_at).trim() || null);
  const reservationId = asString(row.reservation_id).trim();
  const assignee = asString(row.assigned_user_id).trim();

  return (
    <div className="rounded-2xl border border-border/70 bg-background/80 p-3">
      <div className="mb-2 flex flex-wrap items-center gap-1.5">
        {priorityValue ? (
          <StatusBadge
            className="text-[11px]"
            label={localizedPriorityLabel(isEn, priorityValue)}
            tone={priorityTone(priorityValue)}
            value={priorityValue}
          />
        ) : null}
        <StatusBadge
          className="text-[11px]"
          label={statusLabel}
          value={statusValue}
        />
        {typeValue ? (
          <StatusBadge
            className="text-[11px]"
            label={localizedTaskTypeLabel(isEn, typeValue)}
            tone="info"
            value={typeValue}
          />
        ) : null}
        {autoGenerated ? (
          <StatusBadge
            className="text-[11px]"
            label={
              automationSource === "reservation_create"
                ? isEn
                  ? "Auto · create"
                  : "Auto · alta"
                : isEn
                  ? "Auto · transition"
                  : "Auto · transición"
            }
            tone="info"
            value={automationSource || "auto_generated"}
          />
        ) : null}
      </div>

      <p className="line-clamp-2 font-semibold text-xl leading-tight">
        {title || (isEn ? "Task" : "Tarea")}
      </p>

      {description ? (
        <p className="mt-1 line-clamp-2 text-muted-foreground text-sm">
          {description}
        </p>
      ) : null}

      <div className="mt-3 flex items-center justify-between border-border/70 border-t pt-2">
        <div className="flex items-center gap-2">
          <span className="inline-flex h-7 w-7 items-center justify-center rounded-full border border-border/80 bg-muted/30 font-medium text-[11px] uppercase">
            {(assignee || "?").slice(0, 1)}
          </span>
          {reservationId ? (
            <span className="inline-flex items-center gap-1 text-muted-foreground text-xs">
              <Icon icon={Ticket01Icon} size={13} />
              {shortId(reservationId)}
            </span>
          ) : null}
        </div>

        <div className="flex items-center gap-3 text-muted-foreground text-xs">
          {checklistTotal > 0 ? (
            <span className="inline-flex items-center gap-1">
              <Icon icon={Message01Icon} size={13} />
              {checklistCompleted}/{checklistTotal}
            </span>
          ) : null}
          <span className="inline-flex items-center gap-1">
            <Icon icon={Calendar02Icon} size={13} />
            {dueLabel}
          </span>
          <Link
            className="font-medium text-foreground underline-offset-4 hover:underline"
            href={`/module/tasks/${encodeURIComponent(taskId)}`}
          >
            {isEn ? "Open" : "Abrir"}
          </Link>
        </div>
      </div>
    </div>
  );
}
